volumes:
  mysql-utn-udee:

services:
  mysql-utn-udee:
    image: library/mysql:8.0.23
    container_name: mysql-utn-udee
    restart: always
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: udee