CREATE USER 'BACKOFFICE'@'%' IDENTIFIED BY '1234';

GRANT UPDATE ON users TO 'BACKOFFICE';
GRANT INSERT ON users TO 'BACKOFFICE';

GRANT UPDATE ON electric_meters TO 'BACKOFFICE';
GRANT INSERT ON electric_meters TO 'BACKOFFICE';
GRANT DELETE ON electric_meters TO 'BACKOFFICE';

GRANT UPDATE ON tariffs TO 'BACKOFFICE';
GRANT INSERT ON tariffs TO 'BACKOFFICE';
GRANT DELETE ON tariffs TO 'BACKOFFICE';

GRANT UPDATE ON addresses TO 'BACKOFFICE';
GRANT INSERT ON addresses TO 'BACKOFFICE';
GRANT DELETE ON addresses TO 'BACKOFFICE';

CREATE USER 'CLIENT'@'%' IDENTIFIED BY '123';

GRANT SELECT ON measurements TO 'CLIENT';
GRANT SELECT ON bills TO 'CLIENT';
GRANT SELECT ON addresses TO 'CLIENT';

CREATE USER 'METER'@'%' IDENTIFIED BY '12345';

GRANT INSERT ON measurements TO 'METER';